export const API_URLS = {
  LOGIN: `${process.env.REACT_APP_API_URL}/auth/admin/login`,
  // Dashboard
  GETDASHBOARDWIDGET: `${process.env.REACT_APP_API_URL}/dashboard/admin/get-dashboard-widget`,
  GETDASHBOARDDELIERY: `${process.env.REACT_APP_API_URL}/dashboard/admin/get-dashboard-delivery`,
  GETDASHBOARDWEIGHT: `${process.env.REACT_APP_API_URL}/dashboard/admin/get-dashboard-weight`,
  GETDASHBOARDLOYALTY: `${process.env.REACT_APP_API_URL}/dashboard/admin/get-dashboard-loyalty`,
  // Date
  GETDATE: `${process.env.REACT_APP_API_URL}/setting/admin/get-dates`,
  ADDDATE: `${process.env.REACT_APP_API_URL}/setting/admin/add-date`,
  EDITDATE: `${process.env.REACT_APP_API_URL}/setting/admin/edit-date`,
  REMOVEDATE: `${process.env.REACT_APP_API_URL}/setting/admin/remove-date`,
  // Material
  GETMATERIAL: `${process.env.REACT_APP_API_URL}/setting/admin/get-materials`,
  ADDMATERIAL: `${process.env.REACT_APP_API_URL}/setting/admin/add-material`,
  EDITMATERIAL: `${process.env.REACT_APP_API_URL}/setting/admin/edit-material`,
  REMOVEMATERIAL: `${process.env.REACT_APP_API_URL}/setting/admin/remove-material`,
  // Industry
  GETINDUSTRY: `${process.env.REACT_APP_API_URL}/setting/admin/get-industry`,
  ADDINDUSTRY: `${process.env.REACT_APP_API_URL}/setting/admin/add-industry`,
  EDITINDUSTRY: `${process.env.REACT_APP_API_URL}/setting/admin/edit-industry`,
  REMOVEINDUSTRY: `${process.env.REACT_APP_API_URL}/setting/admin/remove-industry`,
  // Color
  GETCOLOR: `${process.env.REACT_APP_API_URL}/setting/admin/get-color`,
  ADDCOLOR: `${process.env.REACT_APP_API_URL}/setting/admin/add-color`,
  EDITCOLOR: `${process.env.REACT_APP_API_URL}/setting/admin/edit-color`,
  REMOVECOLOR: `${process.env.REACT_APP_API_URL}/setting/admin/remove-color`,
  // Residue Materials
  GETRESIDUE: `${process.env.REACT_APP_API_URL}/setting/admin/get-residue-material`,
  ADDRESIDUE: `${process.env.REACT_APP_API_URL}/setting/admin/add-residue-material`,
  EDITRESIDUE: `${process.env.REACT_APP_API_URL}/setting/admin/edit-residue-material`,
  REMOVERESIDUE: `${process.env.REACT_APP_API_URL}/setting/admin/remove-residue-material`,
  // Conditions
  GETCONDITION: `${process.env.REACT_APP_API_URL}/setting/admin/get-condition`,
  ADDCONDITION: `${process.env.REACT_APP_API_URL}/setting/admin/add-condition`,
  EDITCONDITION: `${process.env.REACT_APP_API_URL}/setting/admin/edit-condition`,
  REMOVECONDITION: `${process.env.REACT_APP_API_URL}/setting/admin/remove-condition`,
  // Setting
  GETSETTING: `${process.env.REACT_APP_API_URL}/setting/admin/get-setting`,
  UPDATESETTING: `${process.env.REACT_APP_API_URL}/setting/admin/update-setting`,
  GETALLMATERIALS: `${process.env.REACT_APP_API_URL}/setting/admin/get-allmaterials`,
  GETALLUSERS: `${process.env.REACT_APP_API_URL}/setting/admin/get-allusers`,
  GETALLPACKAGES: `${process.env.REACT_APP_API_URL}/setting/admin/get-allpackages`,
  GETALLQUALITYS: `${process.env.REACT_APP_API_URL}/setting/admin/get-qualitys`,
  // FAG
  GETFAQ: `${process.env.REACT_APP_API_URL}/setting/admin/get-faq`,
  ADDFAQ: `${process.env.REACT_APP_API_URL}/setting/admin/add-faq`,
  EDITFAQ: `${process.env.REACT_APP_API_URL}/setting/admin/edit-faq`,
  REMOVEFAQ: `${process.env.REACT_APP_API_URL}/setting/admin/remove-faq`,
  // Supplier
  GETSUPPLIER: `${process.env.REACT_APP_API_URL}/setting/admin/get-supplier`,
  EDITSUPPLIER: `${process.env.REACT_APP_API_URL}/setting/admin/edit-supplier`,
  REMOVESUPPLIER: `${process.env.REACT_APP_API_URL}/setting/admin/remove-supplier`,
  GETPRICESUPPLIER: `${process.env.REACT_APP_API_URL}/setting/admin/get-price-supplier`,
  SETPRICESUPPLIER: `${process.env.REACT_APP_API_URL}/setting/admin/set-price-supplier`,
  // Delivery
  SETREADDELIVERY: `${process.env.REACT_APP_API_URL}/delivery/admin/set-read-delivery`,
  GETDELIVERY: `${process.env.REACT_APP_API_URL}/delivery/admin/get-delivery`,
  GETSELDELIVERY: `${process.env.REACT_APP_API_URL}/delivery/admin/get-sel-delivery`,
  UPDATESELDELIVERY: `${process.env.REACT_APP_API_URL}/delivery/admin/update-sel-delivery`,
  ADDFEEDBACKDELIVERY: `${process.env.REACT_APP_API_URL}/delivery/admin/add-feedback-delivery`,
  ADDREJECTDELIVERY: `${process.env.REACT_APP_API_URL}/delivery/admin/add-reject-delivery`,
  // Delivery Logs
  GETAllDELIVERYLOGS: `${process.env.REACT_APP_API_URL}/delivery/admin/get-all-deliverylogs`,
  GETSELDELIVERYLOG: `${process.env.REACT_APP_API_URL}/delivery/admin/get-sel-deliverylog`,
}
